name: CI/CD Pipeline for Backend Erklika Pro

on:
  pull_request:
    branches:
      - staging  # Jalankan hanya saat ada perubahan di branch "main"
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy the application to the VPS
      - name: Deploy to GCP
        run: |
          sshpass -p "${{ secrets.GCP_PASSWORD_STAGING }}" ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER_STAGING }} << 'EOF'

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Ini memuat nvm

            nvm use 20 # Pastikan menggunakan Node.js versi 20
            node -v    # Verifikasi versi Node.js
            npm -v     # Verifikasi versi npm

            cd ${{ secrets.DIRECTORY_PATH_STAGING }}
            git restore package-lock.json
            git pull origin staging
            npm install

            export DATABASE_URL=${{ secrets.DATABASE_URL }} 
            export PORT=${{ secrets.PORT }} 
            export DATABASE_URL_ERKLIKA=${{ secrets.DATABASE_URL_ERKLIKA }} 
            export ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} 

            npm run generate
            npm run generate-erklika
            npm run build
            pm2 restart be-erklika-pro --update-env

            # Save PM2 process list
            pm2 save
          EOF
